### ISSUE TITLE
String evaluation

### ISSUE THREAD

**Issue by jmtekin** [lbovet/yglu#12]
I'm not sure if these are bugs but when evaluating strings i get errors in some scenarios where i fell like i shouldn't
In the first example it gives error whenever it evaluates a string containing a "operational" symbol such as / - + . etc. even though the symbol is inside a string. 
![image](https://user-images.githubusercontent.com/60180623/143267967-162188fb-9837-4651-a9c8-d4a2c7537b37.png)

However in this example the error isn't given:
![image](https://user-images.githubusercontent.com/60180623/143271453-7036c816-bc2c-496b-9048-99ee89e77e83.png)

Also why does this work:
![image](https://user-images.githubusercontent.com/60180623/143270454-a48170d1-bbf1-4b30-a0fe-bb3fd5e87140.png)

but not this:
![image](https://user-images.githubusercontent.com/60180623/143270533-d81bf7c0-7353-4718-a5da-0b25b7c9402d.png)

**Comment by lbovet** [comment]
This is because the yaml parser interpret the opening quote when it is at the beginning of the line. It expect then a corresponding closing quote and pass the unquoted content to the expression evaluator.
When the quote is not in the beginning, the yaml parser will pass the content unchanged to the expression evaluator. This is actually complying with the yaml specification.
You can workaround this with mixed double-quoting. The outer quotes will be interpreted by the yaml parser, the inner ones by the expression evaluator.
```yaml
str: !? '"/foo"'
```

**Comment by jmtekin** [comment]
That makes sense. Thank you for the explanation :)
